export const allCountries = [
  {
    id: "CHN",
    flag: "https://flagcdn.com/w320/cn.png",
    name: "China",
    capital: "Beijing",
    population: 1402112000,
    area: 9706961,
    region: "Asia",
    subregion: "Eastern Asia",
    languages: ["Mandarin Chinese"],
    currency: { name: "Chinese Yuan", code: "CNY", symbol: "¥" }
  },
  {
    id: "IND",
    flag: "https://flagcdn.com/w320/in.png",
    name: "India",
    capital: "New Delhi",
    population: 1439323776,
    area: 3287590,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Hindi", "English"],
    currency: { name: "Indian Rupee", code: "INR", symbol: "₹" }
  },
  {
    id: "USA",
    flag: "https://flagcdn.com/w320/us.png",
    name: "United States",
    capital: "Washington, D.C.",
    population: 329484123,
    area: 9372610,
    region: "Americas",
    subregion: "North America",
    languages: ["English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" }
  },
  {
    id: "IDN",
    flag: "https://flagcdn.com/w320/id.png",
    name: "Indonesia",
    capital: "Jakarta",
    population: 273523621,
    area: 1904569,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Indonesian"],
    currency: { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" }
  },
  {
    id: "BRA",
    flag: "https://flagcdn.com/w320/br.png",
    name: "Brazil",
    capital: "Brasília",
    population: 212559409,
    area: 8515767,
    region: "Americas",
    subregion: "South America",
    languages: ["Portuguese"],
    currency: { name: "Brazilian Real", code: "BRL", symbol: "R$" }
  },
  {
    id: "PAK",
    flag: "https://flagcdn.com/w320/pk.png",
    name: "Pakistan",
    capital: "Islamabad",
    population: 220892331,
    area: 881912,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Urdu", "English"],
    currency: { name: "Pakistani Rupee", code: "PKR", symbol: "₨" }
  },
  {
    id: "NGA",
    flag: "https://flagcdn.com/w320/ng.png",
    name: "Nigeria",
    capital: "Abuja",
    population: 206139587,
    area: 923768,
    region: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    currency: { name: "Nigerian Naira", code: "NGN", symbol: "₦" }
  },
  {
    id: "BGD",
    flag: "https://flagcdn.com/w320/bd.png",
    name: "Bangladesh",
    capital: "Dhaka",
    population: 164689383,
    area: 147570,
    region: "Asia",
    subregion: "Southern Asia",
    languages: ["Bengali"],
    currency: { name: "Bangladeshi Taka", code: "BDT", symbol: "৳" }
  },
  {
    id: "RUS",
    flag: "https://flagcdn.com/w320/ru.png",
    name: "Russia",
    capital: "Moscow",
    population: 145912025,
    area: 17098242,
    region: "Europe",
    subregion: "Eastern Europe",
    languages: ["Russian"],
    currency: { name: "Russian Ruble", code: "RUB", symbol: "₽" }
  },
  {
    id: "MEX",
    flag: "https://flagcdn.com/w320/mx.png",
    name: "Mexico",
    capital: "Mexico City",
    population: 128932753,
    area: 1964375,
    region: "Americas",
    subregion: "North America",
    languages: ["Spanish"],
    currency: { name: "Mexican Peso", code: "MXN", symbol: "$" }
  },
  {
    id: "JPN",
    flag: "https://flagcdn.com/w320/jp.png",
    name: "Japan",
    capital: "Tokyo",
    population: 126476458,
    area: 377930,
    region: "Asia",
    subregion: "Eastern Asia",
    languages: ["Japanese"],
    currency: { name: "Japanese Yen", code: "JPY", symbol: "¥" }
  },
  {
    id: "ETH",
    flag: "https://flagcdn.com/w320/et.png",
    name: "Ethiopia",
    capital: "Addis Ababa",
    population: 114963588,
    area: 1104300,
    region: "Africa",
    subregion: "Eastern Africa",
    languages: ["Amharic"],
    currency: { name: "Ethiopian Birr", code: "ETB", symbol: "Br" }
  },
  {
    id: "PHL",
    flag: "https://flagcdn.com/w320/ph.png",
    name: "Philippines",
    capital: "Manila",
    population: 109581085,
    area: 300000,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Filipino", "English"],
    currency: { name: "Philippine Peso", code: "PHP", symbol: "₱" }
  },
  {
    id: "EGY",
    flag: "https://flagcdn.com/w320/eg.png",
    name: "Egypt",
    capital: "Cairo",
    population: 102334403,
    area: 1002450,
    region: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    currency: { name: "Egyptian Pound", code: "EGP", symbol: "E£" }
  },
  {
    id: "VNM",
    flag: "https://flagcdn.com/w320/vn.png",
    name: "Vietnam",
    capital: "Hanoi",
    population: 97338583,
    area: 331212,
    region: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Vietnamese"],
    currency: { name: "Vietnamese Đồng", code: "VND", symbol: "₫" }
  }
  ];